# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Dependencies
    init: |
      sudo apt-get update
      sudo apt-get install -y apache2 mysql-server php7.4-fpm php8.0-fpm php7.4-mysql php8.0-mysql nodejs npm
      sudo systemctl start apache2
      sudo systemctl start mysql
      sudo mysql -e "CREATE DATABASE gitpod;"
      sudo mysql -e "CREATE USER 'gitpod'@'localhost' IDENTIFIED BY 'password';"
      sudo mysql -e "GRANT ALL PRIVILEGES ON gitpod.* TO 'gitpod'@'localhost';"
      sudo mysql -e "FLUSH PRIVILEGES;"
      sudo npm install -g npm
      sudo apt-get install -y default-jdk
      sudo apt-get install -y android-sdk
      sudo apt-get install -y adb
      sudo apt-get install -y gradle
      echo "export ANDROID_HOME=/usr/lib/android-sdk" >> ~/.bashrc
      echo "export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools" >> ~/.bashrc
      source ~/.bashrc