image: gitpod/workspace-full

tasks:
  - name: Install PHP and MariaDB
    init: |
      sudo apt-get update
      sudo apt-get install -y php mariadb-server php-mysql
      sudo mysql_secure_installation
      sudo mysql -e "CREATE DATABASE mydatabase;"
      sudo mysql -e "CREATE USER 'myuser'@'localhost' IDENTIFIED BY 'mypassword';"
      sudo mysql -e "GRANT ALL PRIVILEGES ON mydatabase.* TO 'myuser'@'localhost';"
      sudo mysql -e "FLUSH PRIVILEGES;"
    command: |
      php -S 0.0.0.0:8080 -t public

ports:
  - port: 8080
    onOpen: open-preview